$('.soundOnBtn').click(function(){
    document.getElementById("game-sound").play();
})
$('.soundOffBtn').click(function(){
    document.getElementById("game-sound").pause();
})
$('.startgameBtn').click(function(){
    location.assign('index.html');
})